// Banco de flashcards — CLF-C02
// Distribuição proporcional ao peso real do exame:
// Domínio 1 (24%): 24 cards | Domínio 2 (30%): 30 cards | Domínio 3 (34%): 34 cards | Domínio 4 (12%): 12 cards
// Vá adicionando cards aqui conforme for estudando — é só seguir o mesmo formato { id, d, q, a }

CARDS.push(
// ===== DOMÍNIO 1 — CLOUD CONCEPTS (24 cards) =====
{id:1, d:1, q:"O que é computação em nuvem, segundo a AWS?", a:"É a entrega sob demanda de poder computacional, armazenamento de banco de dados, aplicações e outros recursos de TI pela internet, com preço pay-as-you-go (você paga só pelo que usa)."},
{id:2, d:1, q:"O que significa 'Agilidade' como benefício da nuvem?", a:"A capacidade de provisionar novos recursos rapidamente, em minutos, em vez de semanas ou meses como em um data center tradicional."},
{id:3, d:1, q:"O que é elasticidade na nuvem?", a:"A capacidade de aumentar ou diminuir recursos automaticamente conforme a demanda, pagando apenas pelo que é realmente usado em cada momento."},
{id:4, d:1, q:"O que significa trocar CapEx por OpEx?", a:"Em vez de investir pesado antecipadamente em data centers e servidores (CapEx), você paga despesas operacionais variáveis conforme consome (OpEx), sem investimento inicial alto."},
{id:5, d:1, q:"O que é 'economia de escala' na AWS?", a:"Como a AWS agrega o uso de milhares de clientes, ela consegue custos operacionais mais baixos, e repassa essa economia via reduções de preço ao longo do tempo."},
{id:6, d:1, q:"Por que a nuvem evita o problema de 'adivinhar capacidade'?", a:"Você não precisa mais prever quanta infraestrutura vai precisar com meses de antecedência — escala para cima ou para baixo conforme a demanda real."},
{id:7, d:1, q:"Como a nuvem ajuda a 'ir global em minutos'?", a:"Você pode implantar sua aplicação em múltiplas regiões AWS pelo mundo com poucos cliques, reduzindo latência para usuários globais sem construir infraestrutura física."},
{id:8, d:1, q:"O que é um modelo de implantação em nuvem pública?", a:"Toda a infraestrutura de computação está localizada nas instalações do provedor de nuvem (a AWS), compartilhada entre clientes mas isolada logicamente."},
{id:9, d:1, q:"O que é um modelo de nuvem híbrida?", a:"Conecta infraestrutura on-premises (local) com recursos baseados na nuvem, por exemplo usando AWS Direct Connect, AWS Outposts ou Storage Gateway."},
{id:10, d:1, q:"O que é uma Região AWS?", a:"Uma localização física no mundo onde a AWS agrupa data centers, composta por múltiplas Availability Zones isoladas entre si."},
{id:11, d:1, q:"O que é uma Availability Zone (AZ)?", a:"Um ou mais data centers discretos dentro de uma Região, com energia, refrigeração e rede redundantes, isolados de falhas em outras AZs."},
{id:12, d:1, q:"O que são Edge Locations?", a:"Pontos de presença da AWS usados por serviços como CloudFront e Route 53 para entregar conteúdo com baixa latência, mais próximos dos usuários finais."},
{id:13, d:1, q:"Quais são os 6 pilares do AWS Well-Architected Framework?", a:"Excelência Operacional, Segurança, Confiabilidade, Eficiência de Performance, Otimização de Custos e Sustentabilidade."},
{id:14, d:1, q:"O que avalia o pilar de Excelência Operacional?", a:"A capacidade de rodar e monitorar sistemas para entregar valor de negócio, e melhorar continuamente processos e procedimentos."},
{id:15, d:1, q:"O que avalia o pilar de Confiabilidade?", a:"A capacidade de um sistema se recuperar de falhas de infraestrutura ou serviço, adquirir recursos dinamicamente e mitigar interrupções."},
{id:16, d:1, q:"O que avalia o pilar de Eficiência de Performance?", a:"Usar recursos computacionais de forma eficiente para atender requisitos do sistema, e manter essa eficiência conforme a demanda muda."},
{id:17, d:1, q:"O que avalia o pilar de Otimização de Custos?", a:"Evitar gastos desnecessários e entender onde o dinheiro está sendo gasto, escolhendo o tipo e quantidade certa de recursos."},
{id:18, d:1, q:"O que avalia o pilar de Sustentabilidade?", a:"Minimizar os impactos ambientais de cargas de trabalho em nuvem, como uso de energia e recursos."},
{id:19, d:1, q:"O que é o AWS Cloud Adoption Framework (CAF)?", a:"Um guia de orientações e melhores práticas para ajudar organizações a desenvolver uma estratégia eficiente de adoção da nuvem."},
{id:20, d:1, q:"Quais são as 6 perspectivas do AWS CAF?", a:"Business, People, Governance, Platform, Security e Operations — divididas em perspectivas de negócio (Business, People, Governance) e técnicas (Platform, Security, Operations)."},
{id:21, d:1, q:"O que é a perspectiva 'Governance' do CAF?", a:"Foca em alinhar estratégia de TI com estratégia de negócio, gerenciamento de programas e projetos, e gestão de riscos durante a transformação para a nuvem."},
{id:22, d:1, q:"Quais são as estratégias de migração para a nuvem (os '6 Rs')?", a:"Rehost, Replatform, Repurchase, Refactor/Re-architect, Retain e Retire — formas diferentes de migrar ou tratar cargas de trabalho ao mover para a nuvem."},
{id:23, d:1, q:"O que é 'Rehost' em migração (lift-and-shift)?", a:"Mover uma aplicação para a nuvem sem fazer alterações, replicando a arquitetura existente, geralmente o caminho mais rápido inicialmente."},
{id:24, d:1, q:"Por que a redução de tempo de provisionamento ('go from idea to implementation') é um benefício citado da nuvem?", a:"Porque elimina a necessidade de comprar e configurar hardware fisicamente, permitindo que equipes testem ideias e experimentem rapidamente, com baixo custo de falhar."},

// ===== DOMÍNIO 2 — SECURITY AND COMPLIANCE (30 cards) =====
{id:25, d:2, q:"O que é o Shared Responsibility Model (Modelo de Responsabilidade Compartilhada)?", a:"Define que a AWS é responsável pela segurança 'DA' nuvem (infraestrutura física, hardware, rede global), e o cliente é responsável pela segurança 'NA' nuvem (dados, configurações, gerenciamento de acesso)."},
{id:26, d:2, q:"O que é responsabilidade da AWS no Shared Responsibility Model?", a:"Proteger a infraestrutura global que roda todos os serviços: hardware, software, redes e as instalações físicas dos data centers."},
{id:27, d:2, q:"O que é responsabilidade do cliente no Shared Responsibility Model?", a:"Configuração de segurança do sistema operacional (em EC2), gerenciamento de dados, controle de acesso via IAM, criptografia e configuração de firewall (Security Groups)."},
{id:28, d:2, q:"O que é o AWS IAM?", a:"AWS Identity and Access Management — serviço que controla de forma granular quem está autenticado e autorizado a usar quais recursos na conta AWS."},
{id:29, d:2, q:"O que é um IAM User?", a:"Uma identidade que representa uma pessoa ou aplicação que interage com a AWS, com credenciais próprias de longo prazo."},
{id:30, d:2, q:"O que é um IAM Group?", a:"Uma coleção de IAM users que compartilham as mesmas permissões, facilitando o gerenciamento de acesso em massa."},
{id:31, d:2, q:"O que é uma IAM Role?", a:"Uma identidade com permissões temporárias que pode ser assumida por usuários, aplicações ou serviços AWS, sem precisar de credenciais fixas."},
{id:32, d:2, q:"O que é uma IAM Policy?", a:"Um documento JSON que define permissões — o que uma identidade pode ou não fazer em quais recursos."},
{id:33, d:2, q:"O que é o princípio do menor privilégio (least privilege)?", a:"Conceder apenas as permissões mínimas necessárias para que uma identidade realize sua tarefa, nada além disso."},
{id:34, d:2, q:"Qual é a boa prática para a conta root da AWS?", a:"Bloquear o uso do root no dia a dia, ativar MFA nele, e criar IAM users/roles com permissões específicas para tarefas administrativas."},
{id:35, d:2, q:"O que é MFA na AWS?", a:"Multi-Factor Authentication — exige um segundo fator de verificação (além da senha) para autenticação, aumentando a segurança da conta."},
{id:36, d:2, q:"O que é o AWS IAM Identity Center?", a:"Serviço (antigo AWS SSO) que centraliza o gerenciamento de acesso de usuários a múltiplas contas AWS e aplicações via single sign-on."},
{id:37, d:2, q:"O que é o AWS Organizations?", a:"Serviço que permite gerenciar e governar centralmente múltiplas contas AWS, com faturamento consolidado e políticas aplicadas em toda a organização."},
{id:38, d:2, q:"O que são Service Control Policies (SCPs)?", a:"Políticas do AWS Organizations que definem o limite máximo de permissões que contas-membro podem ter, controlando o que é permitido em toda a organização."},
{id:39, d:2, q:"O que é o Amazon GuardDuty?", a:"Serviço de detecção de ameaças que monitora continuamente atividade maliciosa e comportamento não autorizado, usando machine learning e inteligência de ameaças."},
{id:40, d:2, q:"O que é o Amazon Inspector?", a:"Serviço de avaliação automatizada de segurança que verifica vulnerabilidades e desvios de boas práticas em recursos como EC2 e imagens de containers."},
{id:41, d:2, q:"O que é o Amazon Macie?", a:"Serviço que usa machine learning para descobrir, classificar e proteger dados sensíveis (como dados pessoais) armazenados no Amazon S3."},
{id:42, d:2, q:"Qual a diferença entre AWS Shield Standard e Advanced?", a:"Shield Standard protege gratuitamente contra ataques DDoS comuns; Shield Advanced (pago) oferece proteção mais robusta, suporte 24/7 da equipe DRT e proteção financeira contra picos de custo durante ataques."},
{id:43, d:2, q:"O que é o AWS WAF?", a:"Web Application Firewall — protege aplicações web contra exploits comuns, filtrando tráfego HTTP/HTTPS com regras personalizáveis."},
{id:44, d:2, q:"O que é o AWS KMS?", a:"Key Management Service — serviço gerenciado para criar e controlar chaves de criptografia usadas para proteger dados em diversos serviços AWS."},
{id:45, d:2, q:"O que é o AWS Secrets Manager?", a:"Serviço para armazenar, gerenciar e rotacionar com segurança credenciais como senhas de banco de dados, chaves de API e outros segredos."},
{id:46, d:2, q:"O que é o AWS Certificate Manager (ACM)?", a:"Serviço que provisiona, gerencia e renova certificados SSL/TLS gratuitamente para uso com serviços AWS como CloudFront e Load Balancers."},
{id:47, d:2, q:"O que é o AWS Artifact?", a:"Portal de autoatendimento que dá acesso sob demanda a relatórios de conformidade da AWS (como SOC, PCI) e acordos de segurança, como o Business Associate Addendum."},
{id:48, d:2, q:"O que o AWS Trusted Advisor verifica na categoria de segurança?", a:"Configurações que fogem das boas práticas, como buckets S3 públicos, MFA não habilitado no root, e portas excessivamente abertas em Security Groups."},
{id:49, d:2, q:"Qual a diferença entre criptografia em trânsito e em repouso?", a:"Em trânsito protege dados enquanto trafegam pela rede (ex: TLS/HTTPS); em repouso protege dados armazenados em disco (ex: criptografia no S3 ou EBS)."},
{id:50, d:2, q:"Qual a diferença entre Security Groups e Network ACLs?", a:"Security Groups operam no nível da instância e são stateful (somente regras 'allow'); NACLs operam no nível da subnet e são stateless (permitem regras 'allow' e 'deny')."},
{id:51, d:2, q:"O que é o AWS Config?", a:"Serviço que avalia, audita e registra continuamente as configurações dos recursos AWS, permitindo verificar conformidade ao longo do tempo."},
{id:52, d:2, q:"O que é o AWS CloudTrail?", a:"Serviço que registra todas as chamadas de API feitas na conta AWS, permitindo auditoria, rastreamento de mudanças e investigação de segurança."},
{id:53, d:2, q:"Como o AWS Artifact ajuda com compliance como HIPAA, GDPR e PCI-DSS?", a:"Disponibiliza relatórios e certificações de auditoria de terceiros que comprovam que a infraestrutura AWS atende a esses padrões — a aplicação do cliente sobre essa infraestrutura ainda precisa ser configurada corretamente."},
{id:54, d:2, q:"O que é Network ACL por padrão em uma VPC nova?", a:"A NACL padrão permite todo o tráfego de entrada e saída; NACLs customizadas, por padrão, negam todo o tráfego até que regras sejam adicionadas."},

// ===== DOMÍNIO 3 — CLOUD TECHNOLOGY AND SERVICES (34 cards) =====
{id:55, d:3, q:"O que é o Amazon EC2?", a:"Elastic Compute Cloud — serviço que fornece capacidade de computação redimensionável na nuvem, na forma de servidores virtuais (instâncias)."},
{id:56, d:3, q:"O que são famílias de instância EC2 (ex: t, m, c, r)?", a:"Agrupam instâncias otimizadas para diferentes perfis: t/m são de uso geral, c é otimizada para computação, r é otimizada para memória, entre outras."},
{id:57, d:3, q:"O que é o AWS Lambda?", a:"Serviço de computação serverless que executa código em resposta a eventos, sem que você precise provisionar ou gerenciar servidores; você paga só pelo tempo de execução."},
{id:58, d:3, q:"O que é o AWS Elastic Beanstalk?", a:"Serviço que facilita o deploy e gerenciamento de aplicações, cuidando automaticamente do provisionamento de infraestrutura (EC2, load balancer, auto scaling)."},
{id:59, d:3, q:"O que é o Amazon ECS?", a:"Elastic Container Service — serviço de orquestração de containers Docker, totalmente gerenciado pela AWS."},
{id:60, d:3, q:"O que é o Amazon EKS?", a:"Elastic Kubernetes Service — serviço gerenciado que facilita rodar Kubernetes na AWS sem precisar instalar e operar o plano de controle."},
{id:61, d:3, q:"O que é o AWS Fargate?", a:"Mecanismo de computação serverless para containers, usado com ECS ou EKS, que elimina a necessidade de gerenciar servidores ou clusters."},
{id:62, d:3, q:"O que é o AWS Outposts?", a:"Permite rodar infraestrutura e serviços nativos da AWS fisicamente on-premises, oferecendo experiência híbrida consistente com a nuvem."},
{id:63, d:3, q:"O que é o Amazon S3?", a:"Simple Storage Service — armazenamento de objetos altamente durável e escalável, usado para guardar qualquer tipo de arquivo na nuvem."},
{id:64, d:3, q:"Quais são as principais classes de armazenamento do S3?", a:"S3 Standard (acesso frequente), S3 Intelligent-Tiering, S3 Standard-IA e One Zone-IA (acesso infrequente), e S3 Glacier/Glacier Deep Archive (arquivamento de longo prazo, baixo custo)."},
{id:65, d:3, q:"O que é o Amazon EBS?", a:"Elastic Block Store — armazenamento em blocos persistente, usado como 'disco rígido' anexado a instâncias EC2."},
{id:66, d:3, q:"O que é o Amazon EFS?", a:"Elastic File System — sistema de arquivos compartilhado e escalável, que pode ser montado simultaneamente por múltiplas instâncias EC2."},
{id:67, d:3, q:"O que é o AWS Storage Gateway?", a:"Serviço híbrido que conecta ambientes on-premises ao armazenamento em nuvem da AWS, útil para backup e arquivamento gradual."},
{id:68, d:3, q:"O que é a AWS Snow Family?", a:"Dispositivos físicos (Snowcone, Snowball, Snowmobile) usados para migrar grandes volumes de dados para a AWS quando a transferência pela internet não é viável."},
{id:69, d:3, q:"O que é o Amazon RDS?", a:"Relational Database Service — serviço gerenciado de bancos de dados relacionais (MySQL, PostgreSQL, SQL Server etc.), que cuida de patches, backups e replicação."},
{id:70, d:3, q:"O que é o Amazon Aurora?", a:"Banco de dados relacional compatível com MySQL e PostgreSQL, desenvolvido pela AWS, com maior performance e disponibilidade que os engines tradicionais."},
{id:71, d:3, q:"O que é o Amazon DynamoDB?", a:"Banco de dados NoSQL serverless de chave-valor/documento, totalmente gerenciado, com performance de milissegundos em qualquer escala."},
{id:72, d:3, q:"O que é o Amazon Redshift?", a:"Serviço de data warehouse totalmente gerenciado, otimizado para análise de grandes volumes de dados e consultas analíticas complexas."},
{id:73, d:3, q:"O que é o Amazon ElastiCache?", a:"Serviço de cache em memória (Redis ou Memcached) que melhora a performance de aplicações reduzindo a carga em bancos de dados."},
{id:74, d:3, q:"O que é o Amazon VPC?", a:"Virtual Private Cloud — uma rede virtual logicamente isolada dentro da AWS, onde você define IPs, sub-redes, rotas e gateways."},
{id:75, d:3, q:"Qual a diferença entre subnet pública e privada em uma VPC?", a:"Subnet pública tem rota para um Internet Gateway (acessível pela internet); subnet privada não tem essa rota direta, geralmente usada para recursos internos como bancos de dados."},
{id:76, d:3, q:"O que é um Internet Gateway?", a:"Componente da VPC que permite comunicação entre recursos em uma subnet pública e a internet."},
{id:77, d:3, q:"O que é um NAT Gateway?", a:"Permite que instâncias em subnets privadas iniciem conexões de saída para a internet (ex: para atualizações), sem permitir conexões de entrada vindas da internet."},
{id:78, d:3, q:"O que é o Amazon Route 53?", a:"Serviço de DNS gerenciado e escalável da AWS, também usado para registro de domínios e roteamento de tráfego com checagem de saúde."},
{id:79, d:3, q:"O que é o Amazon CloudFront?", a:"Rede de distribuição de conteúdo (CDN) que entrega dados, vídeos e APIs com baixa latência, usando a rede global de edge locations da AWS."},
{id:80, d:3, q:"O que é o Elastic Load Balancing (ELB)?", a:"Distribui automaticamente tráfego de entrada entre múltiplos alvos (instâncias EC2, containers, IPs), aumentando disponibilidade e tolerância a falhas."},
{id:81, d:3, q:"O que é o AWS Direct Connect?", a:"Estabelece uma conexão de rede privada e dedicada entre o data center on-premises do cliente e a AWS, com latência mais baixa e consistente que a internet pública."},
{id:82, d:3, q:"O que é o AWS CloudFormation?", a:"Serviço de Infrastructure as Code (IaC) que permite definir e provisionar recursos AWS através de templates declarativos (JSON/YAML)."},
{id:83, d:3, q:"O que é o Amazon CloudWatch?", a:"Serviço de monitoramento que coleta métricas, logs e eventos de recursos AWS, permitindo criar dashboards e alarmes."},
{id:84, d:3, q:"O que é o AWS Auto Scaling?", a:"Ajusta automaticamente a capacidade computacional (ex: número de instâncias EC2) para manter performance estável a um custo mínimo, conforme a demanda muda."},
{id:85, d:3, q:"O que é o Amazon SNS?", a:"Simple Notification Service — serviço de mensageria pub/sub que envia notificações para múltiplos assinantes (e-mail, SMS, filas, Lambda etc.)."},
{id:86, d:3, q:"O que é o Amazon SQS?", a:"Simple Queue Service — serviço de filas de mensagens totalmente gerenciado, usado para desacoplar componentes de uma aplicação."},
{id:87, d:3, q:"O que é o Amazon SageMaker?", a:"Serviço totalmente gerenciado para construir, treinar e implantar modelos de machine learning em escala."},
{id:88, d:3, q:"O que é o Amazon Bedrock?", a:"Serviço que dá acesso via API a modelos fundacionais de IA generativa de diversas empresas, para construir aplicações de IA generativa sem gerenciar infraestrutura."},

// ===== DOMÍNIO 4 — BILLING, PRICING, AND SUPPORT (12 cards) =====
{id:89, d:4, q:"Como funciona o modelo de precificação On-Demand do EC2?", a:"Você paga por capacidade computacional por hora ou segundo, sem compromissos de longo prazo nem pagamento antecipado — ideal para cargas variáveis ou imprevisíveis."},
{id:90, d:4, q:"O que são Reserved Instances?", a:"Compromisso de uso de 1 ou 3 anos em troca de descontos significativos (até ~72%) comparado ao preço On-Demand, ideal para cargas previsíveis e constantes."},
{id:91, d:4, q:"O que são Spot Instances?", a:"Capacidade EC2 ociosa vendida com desconto de até 90%, que pode ser interrompida pela AWS com pouco aviso — ideal para workloads tolerantes a interrupção."},
{id:92, d:4, q:"O que são Savings Plans?", a:"Modelo de desconto flexível baseado em compromisso de gasto (USD/hora) por 1 ou 3 anos, aplicável a diferentes tipos e tamanhos de instância, ao contrário das Reserved Instances."},
{id:93, d:4, q:"O que é o AWS Free Tier?", a:"Oferece acesso gratuito limitado a diversos serviços AWS por 12 meses (para novas contas) ou de forma sempre gratuita (always free), dependendo do serviço."},
{id:94, d:4, q:"O que é a AWS Pricing Calculator?", a:"Ferramenta gratuita que permite estimar o custo mensal de uma arquitetura AWS antes de implantá-la, sem precisar de uma conta AWS."},
{id:95, d:4, q:"O que é o AWS Cost Explorer?", a:"Ferramenta que permite visualizar, analisar e entender padrões de custo e uso da AWS ao longo do tempo, com gráficos e previsões."},
{id:96, d:4, q:"O que é o AWS Budgets?", a:"Permite definir orçamentos personalizados de custo ou uso, com alertas automáticos quando os gastos reais ou previstos ultrapassam o limite definido."},
{id:97, d:4, q:"O que é o Consolidated Billing no AWS Organizations?", a:"Combina o faturamento de múltiplas contas AWS em uma única fatura, e permite aproveitar descontos por volume agregado entre todas as contas."},
{id:98, d:4, q:"O que o plano de suporte Basic da AWS inclui?", a:"Incluso gratuitamente em todas as contas: acesso a documentação, fóruns, Trusted Advisor (verificações básicas) e Personal Health Dashboard — sem suporte técnico direto."},
{id:99, d:4, q:"Quais são os planos de suporte pagos da AWS, do mais básico ao mais completo?", a:"Developer, Business e Enterprise (com Enterprise On-Ramp como intermediário) — cada nível oferece tempos de resposta mais rápidos e acesso a mais recursos, como Technical Account Manager (TAM) no Enterprise."},
{id:100, d:4, q:"O que é o AWS Marketplace?", a:"Catálogo digital onde clientes podem encontrar, comprar e implantar software de terceiros que já roda na infraestrutura AWS, com cobrança integrada à fatura AWS."}
);
