// Flashcards dos módulos do curso AWS re/Start (Escola da Nuvem)
// Cobre temas mais amplos/práticos do curso, além do escopo estrito do exame CLF-C02.
// Estrutura por módulo do curso (não por peso oficial de exame, já que não é conteúdo de prova).
// COURSE_MODULES e COURSE_CARDS já são declarados no <script> inline do index.html.

COURSE_CARDS.push(

// ===== 1. Redes na AWS =====
{id:1, m:1, q:"O que é VPC Peering?", a:"Uma conexão de rede entre duas VPCs que permite que elas se comuniquem usando IPs privados, como se estivessem na mesma rede — sem passar pela internet pública."},
{id:2, m:1, q:"Qual a diferença entre uma tabela de rotas (route table) associada a uma subnet pública e uma privada?", a:"A tabela da subnet pública tem uma rota para o Internet Gateway (0.0.0.0/0 → IGW); a da subnet privada não tem essa rota direta, geralmente apontando para um NAT Gateway se precisar de saída."},
{id:3, m:1, q:"Quando usar AWS VPN em vez de AWS Direct Connect para conectar um data center à AWS?", a:"VPN é mais rápido de configurar e mais barato, ideal para conexões temporárias ou de backup; Direct Connect exige mais setup mas oferece conexão dedicada, mais estável e com menor latência para uso contínuo."},
{id:4, m:1, q:"O que verificar primeiro ao solucionar um problema de conectividade em uma VPC?", a:"Route tables (existe rota para o destino?), Security Groups e NACLs (o tráfego está sendo permitido?), e se a subnet é realmente pública ou privada conforme esperado."},
{id:5, m:1, q:"O que é um Bastion Host (ou jump box) em uma arquitetura de VPC?", a:"Uma instância em uma subnet pública usada como ponto de acesso controlado para gerenciar instâncias em subnets privadas, sem expor essas instâncias diretamente à internet."},
{id:6, m:1, q:"Por que planejar bem o bloco CIDR de uma VPC antes de criá-la é importante?", a:"Porque o range de IP de uma VPC não pode ser facilmente alterado depois, e um planejamento ruim pode causar conflitos ao conectar essa VPC com outras redes (peering, VPN) no futuro."},

// ===== 2. Introdução à Segurança =====
{id:7, m:2, q:"Qual a primeira linha de defesa ao configurar o acesso de rede de uma instância EC2?", a:"O Security Group da instância — ele define quais portas e origens de tráfego têm permissão de acesso, funcionando como um firewall virtual na própria instância."},
{id:8, m:2, q:"Por que é uma boa prática revisar regularmente as regras dos Security Groups de uma conta?", a:"Regras esquecidas (como uma porta aberta para 0.0.0.0/0 durante um teste) podem virar brechas de segurança se não forem removidas depois de usadas."},
{id:9, m:2, q:"O que o AWS CloudTrail registra que ajuda a investigar um incidente de segurança?", a:"Todas as chamadas de API feitas na conta — quem fez o quê, quando, e de onde — permitindo reconstruir a linha do tempo de uma ação suspeita."},
{id:10, m:2, q:"Qual é a função prática do AWS Config no dia a dia de uma equipe de segurança?", a:"Alertar quando a configuração de um recurso muda de um jeito que viola uma regra definida (por exemplo, um Security Group passando a permitir tráfego irrestrito), além de manter o histórico dessas mudanças."},
{id:11, m:2, q:"Que tipo de recomendação o AWS Trusted Advisor dá na categoria de segurança?", a:"Alerta sobre configurações de risco, como buckets S3 públicos, portas abertas demais em Security Groups, e MFA não habilitado na conta root."},
{id:12, m:2, q:"Quais são boas práticas recomendadas logo na criação de uma nova conta AWS?", a:"Ativar MFA na conta root, não usar a conta root no dia a dia, criar um IAM user administrativo, e configurar alertas de billing para detectar uso inesperado cedo."},

// ===== 3. Bases de Dados =====
{id:13, m:3, q:"O que é Multi-AZ no Amazon RDS?", a:"Uma configuração que mantém uma réplica síncrona do banco em outra Availability Zone, promovida automaticamente em caso de falha na instância principal — usada para alta disponibilidade, não para performance de leitura."},
{id:14, m:3, q:"O que é uma Read Replica no RDS, e para que serve?", a:"Uma cópia assíncrona do banco de dados usada para distribuir carga de leitura, aliviando a instância principal — diferente do Multi-AZ, que é focado em disponibilidade."},
{id:15, m:3, q:"O que é a partition key no DynamoDB, e por que ela é importante?", a:"É o atributo usado para distribuir os dados entre as partições internas do DynamoDB; uma boa escolha de partition key evita 'hot partitions' e garante performance uniforme."},
{id:16, m:3, q:"Qual a diferença entre os modos de capacidade 'Provisioned' e 'On-Demand' no DynamoDB?", a:"No Provisioned você define quanta capacidade de leitura/escrita reservar (mais barato para tráfego previsível); no On-Demand a capacidade escala automaticamente conforme o uso real, sem planejamento prévio."},
{id:17, m:3, q:"Quando escolher DynamoDB em vez de RDS para uma nova aplicação?", a:"Quando os dados são mais simples (chave-valor/documento), a escala e a latência baixíssima são prioridade, e não há necessidade de relacionamentos complexos ou consultas SQL avançadas."},
{id:18, m:3, q:"O que interagir com um banco de dados 'usando uma aplicação' geralmente exige, do ponto de vista de rede?", a:"Que a aplicação (por exemplo, rodando em uma instância EC2) tenha rota de rede até a instância do banco e que o Security Group do banco permita tráfego de entrada vindo da aplicação, na porta correta."},

// ===== 4. Arquitetura AWS =====
{id:19, m:4, q:"Na prática, o que significa aplicar o pilar de Confiabilidade em uma arquitetura real?", a:"Projetar para que a falha de um componente (uma instância, uma AZ) não derrube o sistema inteiro — por exemplo, usando Auto Scaling, Multi-AZ e balanceamento de carga."},
{id:20, m:4, q:"Por que alta disponibilidade (HA) não é o mesmo que tolerância a falhas (fault tolerance)?", a:"Alta disponibilidade minimiza o tempo de inatividade (pode haver uma pequena interrupção durante o failover); tolerância a falhas busca zero interrupção perceptível, geralmente com redundância mais cara e complexa."},
{id:21, m:4, q:"Quais fatores uma empresa tipicamente avalia ao planejar a transição de um data center para a nuvem?", a:"Custo total de propriedade (TCO), dependências entre sistemas, requisitos de conformidade, tolerância a downtime durante a migração, e qual estratégia de migração (dos 6 Rs) faz sentido para cada carga de trabalho."},
{id:22, m:4, q:"Como o Well-Architected Framework ajuda times técnicos durante o design de uma nova arquitetura?", a:"Fornece um checklist estruturado de perguntas por pilar (segurança, confiabilidade, custo etc.) pra identificar riscos e trade-offs antes de construir, em vez de descobri-los depois em produção."},
{id:23, m:4, q:"O que caracteriza um único ponto de falha (single point of failure) em uma arquitetura?", a:"Um componente cuja falha derruba o sistema inteiro — por exemplo, uma única instância EC2 sem redundância nem Auto Scaling atendendo todo o tráfego."},
{id:24, m:4, q:"Por que redundância geográfica (múltiplas AZs ou Regiões) é um princípio central de design na AWS?", a:"Porque distribui o risco: a falha de um data center físico (AZ) não compromete a aplicação inteira, já que outras AZs continuam disponíveis."},

// ===== 5. Operações de Sistema =====
{id:25, m:5, q:"Qual é o objetivo de uma base de conhecimento (knowledge base) de troubleshooting em uma equipe de operações?", a:"Documentar problemas já resolvidos e suas soluções, pra acelerar a resolução de incidentes parecidos no futuro e reduzir dependência de uma única pessoa que 'sabe tudo'."},
{id:26, m:5, q:"O que é necessário configurar antes de usar a AWS CLI pela primeira vez?", a:"Rodar 'aws configure' e fornecer o Access Key ID, Secret Access Key, região padrão e formato de saída — essas credenciais geralmente vêm de um IAM user com as permissões necessárias."},
{id:27, m:5, q:"Por que se recomenda usar IAM roles em vez de access keys fixas ao rodar a AWS CLI a partir de uma instância EC2?", a:"Roles fornecem credenciais temporárias gerenciadas automaticamente pela AWS, eliminando o risco de uma access key fixa vazar ou ficar esquecida em algum lugar."},
{id:28, m:5, q:"Qual é a vantagem prática de usar a AWS CLI em vez do Console para tarefas repetitivas?", a:"Permite automatizar via scripts, repetir a mesma operação de forma consistente, e integrar com pipelines — algo inviável de fazer manualmente clicando no Console toda vez."},
{id:29, m:5, q:"O que significa 'operações de sistema' no contexto AWS, de forma resumida?", a:"O conjunto de práticas para manter sistemas rodando de forma confiável em produção: monitoramento, resposta a incidentes, automação de tarefas rotineiras e documentação de processos."},

// ===== 6. Ferramentas e Automação =====
{id:30, m:6, q:"O que é o AWS Systems Manager Run Command?", a:"Permite executar comandos remotamente em múltiplas instâncias EC2 simultaneamente, sem precisar acessar cada uma individualmente via SSH."},
{id:31, m:6, q:"O que é o AWS Systems Manager Patch Manager?", a:"Automatiza a aplicação de patches de segurança e atualizações do sistema operacional em instâncias EC2, em escala e de forma agendada."},
{id:32, m:6, q:"O que é o AWS Systems Manager Session Manager, e por que ele é mais seguro que SSH tradicional?", a:"Permite acessar o terminal de uma instância EC2 pelo navegador ou CLI, sem precisar abrir a porta 22 nem gerenciar chaves SSH — reduzindo a superfície de ataque."},
{id:33, m:6, q:"O que é o Parameter Store, dentro do Systems Manager?", a:"Um repositório para armazenar de forma segura configurações e segredos (como strings de conexão, senhas), que aplicações podem buscar em tempo de execução em vez de hardcodar no código."},
{id:34, m:6, q:"Qual é a vantagem geral de investir em automação de tarefas administrativas na AWS?", a:"Reduz erro humano, economiza tempo em tarefas repetitivas, e permite que a equipe escale operações sem precisar crescer proporcionalmente em número de pessoas."},

// ===== 7. Servidores =====
{id:35, m:7, q:"O que é necessário configurar em um bucket S3 para hospedar um site estático?", a:"Habilitar 'Static website hosting', definir o documento de índice (ex: index.html), e configurar uma política de bucket que permita leitura pública dos arquivos."},
{id:36, m:7, q:"Quais são erros comuns ao tentar criar uma instância EC2 pela primeira vez?", a:"Esquecer de associar um key pair (impossibilitando acesso SSH), escolher uma subnet sem rota de internet quando precisa de acesso externo, ou deixar o Security Group sem a porta necessária aberta."},
{id:37, m:7, q:"O que o AWS Elastic Beanstalk automatiza que, de outra forma, precisaria ser feito manualmente?", a:"Provisionamento de infraestrutura (EC2, Load Balancer, Auto Scaling), deploy de versões da aplicação, e monitoramento básico de saúde — o desenvolvedor só entrega o código."},
{id:38, m:7, q:"Se uma instância EC2 não consegue ser acessada via navegador após o lançamento, qual é geralmente o primeiro ponto a verificar?", a:"O Security Group da instância — verificar se a porta usada pela aplicação (ex: 80 ou 443) está liberada para a origem correta."},
{id:39, m:7, q:"Qual a diferença prática entre gerenciar servidores 'na mão' via EC2 e usar o Elastic Beanstalk?", a:"Com EC2 puro, você controla e configura cada peça da infraestrutura manualmente; com Elastic Beanstalk, a AWS gerencia essa infraestrutura por trás dos panos, e você foca só no código da aplicação."},

// ===== 8. Escala e Resolução de Nomes =====
{id:40, m:8, q:"Qual a diferença entre um Application Load Balancer (ALB) e um Network Load Balancer (NLB)?", a:"O ALB opera na camada 7 (HTTP/HTTPS), com roteamento baseado em conteúdo da requisição; o NLB opera na camada 4 (TCP/UDP), com performance extremamente alta e baixa latência, mas sem inspecionar o conteúdo da requisição."},
{id:41, m:8, q:"O que é um listener em um Elastic Load Balancer?", a:"Uma regra que define em qual porta e protocolo o load balancer escuta requisições, e para qual target group elas devem ser encaminhadas."},
{id:42, m:8, q:"Qual a diferença entre um Launch Configuration e um Launch Template no Auto Scaling?", a:"Launch Template é a versão mais moderna e flexível, com suporte a versionamento e mais opções de configuração; Launch Configuration é o modelo mais antigo e mais limitado, hoje descontinuado para novos usos."},
{id:43, m:8, q:"O que é uma política de scaling (scaling policy) no Auto Scaling?", a:"Uma regra que define quando adicionar ou remover instâncias, geralmente baseada em métricas do CloudWatch, como uso de CPU acima de um limite."},
{id:44, m:8, q:"O que é roteamento por failover no Amazon Route 53?", a:"Uma política de roteamento que direciona tráfego para um recurso primário, e automaticamente muda para um recurso secundário se o primário falhar em um health check."},
{id:45, m:8, q:"Além de failover, quais outras políticas de roteamento o Route 53 oferece?", a:"Simples, ponderado (weighted), baseado em latência, geolocalização, geoproximidade e multivalor, entre outras — cada uma pra um objetivo diferente de distribuição de tráfego."},

// ===== 9. Sem Servidor e Contêineres =====
{id:46, m:9, q:"Quais tipos de eventos podem disparar (trigger) uma função AWS Lambda?", a:"Diversos: upload em um bucket S3, uma requisição via API Gateway, uma mensagem em uma fila SQS, um evento agendado (cron), entre muitos outros integrados a serviços AWS."},
{id:47, m:9, q:"Qual a diferença entre uma API REST e uma API HTTP no Amazon API Gateway?", a:"APIs HTTP são mais simples, rápidas e baratas, ideais para a maioria dos casos com Lambda; APIs REST oferecem recursos mais avançados (como cache e validação de request), mas com mais custo e complexidade."},
{id:48, m:9, q:"O que é uma máquina de estados (state machine) no AWS Step Functions?", a:"Uma forma visual e declarativa de orquestrar múltiplos passos de um fluxo (como várias funções Lambda em sequência ou paralelo), com tratamento de erro e retry integrados."},
{id:49, m:9, q:"O que é uma task definition no Amazon ECS?", a:"Um blueprint que descreve como um container deve rodar: qual imagem usar, quanto de CPU/memória alocar, quais portas expor, entre outras configurações."},
{id:50, m:9, q:"Qual a diferença prática entre rodar containers no ECS com launch type EC2 versus Fargate?", a:"Com EC2, você gerencia as instâncias que hospedam os containers; com Fargate, a AWS gerencia essa infraestrutura por trás dos panos — você só define o container, sem lidar com servidores."},
{id:51, m:9, q:"O que é uma imagem de container, de forma resumida?", a:"Um pacote imutável contendo tudo que uma aplicação precisa pra rodar (código, dependências, configurações), usado para criar containers em execução de forma consistente em qualquer ambiente."},

// ===== 10. Serviços de Banco de Dados =====
{id:52, m:10, q:"Para qual tipo de carga de trabalho o Amazon Redshift é mais indicado, comparado ao RDS?", a:"Redshift é otimizado para análises complexas sobre grandes volumes de dados históricos (OLAP); RDS é mais indicado para transações do dia a dia de uma aplicação (OLTP)."},
{id:53, m:10, q:"Como o Amazon Aurora consegue maior disponibilidade que um banco relacional tradicional?", a:"Replica os dados automaticamente entre múltiplas Availability Zones, com failover rápido e armazenamento distribuído projetado para alta durabilidade."},
{id:54, m:10, q:"Quais são as duas etapas principais de uma migração de banco de dados usando AWS DMS e SCT juntos?", a:"O SCT converte o esquema/código do banco de origem para o formato do banco de destino; o DMS realiza a migração e replicação contínua dos dados em si."},
{id:55, m:10, q:"O que é importante avaliar antes de migrar um banco de dados on-premises para o Amazon RDS?", a:"Compatibilidade do engine de banco, tamanho dos dados (tempo de transferência), tolerância a downtime durante o corte (cutover), e se será uma migração homogênea (mesmo engine) ou heterogênea (engine diferente)."},
{id:56, m:10, q:"O que significa uma migração de banco de dados 'homogênea'?", a:"Quando o banco de origem e o de destino usam o mesmo motor (engine) de banco de dados, por exemplo MySQL para MySQL — geralmente mais simples que uma migração heterogênea."},

// ===== 11. Serviços de Rede =====
{id:57, m:11, q:"Qual a diferença entre AWS Transit Gateway e VPC Peering para conectar múltiplas VPCs?", a:"VPC Peering conecta VPCs par a par, o que fica complexo com muitas VPCs; Transit Gateway atua como um hub central, simplificando a conectividade entre dezenas de VPCs e redes on-premises."},
{id:58, m:11, q:"Quais opções de conectividade existem entre uma rede on-premises e uma VPC?", a:"AWS Site-to-Site VPN (conexão criptografada pela internet) e AWS Direct Connect (conexão física dedicada), podendo inclusive serem combinadas como backup uma da outra."},
{id:59, m:11, q:"Ao investigar um problema de rede em uma VPC, por que verificar tanto Security Groups quanto NACLs?", a:"Porque ambos podem estar bloqueando o tráfego por razões diferentes — o Security Group na instância (stateful) e a NACL na subnet (stateless) — um problema pode estar em qualquer um dos dois, ou nos dois."},
{id:60, m:11, q:"Como a resolução de nomes (DNS) funciona dentro de uma VPC por padrão?", a:"A AWS fornece um resolvedor DNS interno na VPC (geralmente no endereço base +2 do CIDR), que resolve nomes de domínio para recursos dentro e fora da AWS automaticamente, sem configuração extra."},
{id:61, m:11, q:"O que verificar quando duas instâncias na mesma VPC, em subnets diferentes, não conseguem se comunicar?", a:"Se as tabelas de rotas de ambas as subnets têm rota uma para a outra (geralmente automático dentro da mesma VPC) e se os Security Groups permitem o tráfego entre elas."},

// ===== 12. Armazenamento e Arquivamento =====
{id:62, m:12, q:"Qual a diferença entre os tipos de volume EBS gp3 e io2?", a:"gp3 é de uso geral, com bom equilíbrio de custo e performance para a maioria das cargas; io2 é otimizado para IOPS altíssimo e consistente, indicado para bancos de dados críticos de alta performance."},
{id:63, m:12, q:"Qual a diferença entre Instance Store e Amazon EBS?", a:"Instance Store é armazenamento temporário fisicamente anexado ao hardware do host, perdido se a instância parar ou for encerrada; EBS é persistente e independente do ciclo de vida da instância."},
{id:64, m:12, q:"Quando usar Amazon EFS em vez de Amazon EBS?", a:"Quando múltiplas instâncias EC2 precisam acessar e escrever no mesmo sistema de arquivos simultaneamente — EBS só pode ser anexado a uma instância por vez (exceto volumes multi-attach específicos)."},
{id:65, m:12, q:"Quais são as opções de recuperação (retrieval) de dados no S3 Glacier, e qual a diferença entre elas?", a:"Expedited (minutos, mais caro), Standard (horas) e Bulk (mais barato, mas pode levar até 12 horas) — a escolha depende da urgência em recuperar os dados arquivados."},
{id:66, m:12, q:"Qual a diferença entre AWS Storage Gateway e AWS Transfer Family?", a:"Storage Gateway conecta um ambiente on-premises ao armazenamento AWS de forma híbrida e contínua; Transfer Family facilita a transferência de arquivos via protocolos como SFTP/FTPS diretamente para o S3."},

// ===== 13. Monitoramento e Segurança =====
{id:67, m:13, q:"Qual a diferença entre uma métrica e um alarme no Amazon CloudWatch?", a:"A métrica é o dado numérico monitorado ao longo do tempo (ex: uso de CPU); o alarme é uma regra que dispara uma ação (como notificação ou Auto Scaling) quando essa métrica ultrapassa um limite definido."},
{id:68, m:13, q:"O que o CloudWatch Logs Insights permite fazer?", a:"Rodar consultas estruturadas sobre grandes volumes de logs para encontrar padrões, erros ou eventos específicos, sem precisar processar os logs manualmente."},
{id:69, m:13, q:"Como o Amazon Athena pode ser usado junto com o AWS CloudTrail?", a:"Permite rodar consultas SQL diretamente sobre os logs do CloudTrail armazenados no S3, facilitando investigações de segurança sem precisar carregar os dados em outro sistema."},
{id:70, m:13, q:"Por que monitoramento proativo (alarmes) é mais valioso que monitoramento reativo (só olhar quando algo já quebrou)?", a:"Alarmes permitem agir antes que um problema afete usuários — por exemplo, escalando recursos automaticamente antes de um gargalo de performance virar uma indisponibilidade."},

// ===== 14. Gerenciando o Consumo de Recursos =====
{id:71, m:14, q:"Como a estrutura de Organizational Units (OUs) no AWS Organizations ajuda a gerenciar múltiplas contas?", a:"Permite agrupar contas com necessidades parecidas (ex: produção, desenvolvimento) e aplicar políticas (como SCPs) de forma centralizada a cada grupo, em vez de conta por conta."},
{id:72, m:14, q:"O que é uma tag (etiqueta) de recurso na AWS, e para que serve na prática?", a:"Um par chave-valor associado a um recurso (ex: 'ambiente: produção'), usado para organizar, filtrar e principalmente alocar custos entre times ou projetos nos relatórios de billing."},
{id:73, m:14, q:"Por que uma estratégia de tagging consistente é importante em uma organização com muitas contas e recursos?", a:"Sem tags padronizadas, fica quase impossível saber quanto cada time ou projeto está gastando, ou identificar recursos órfãos/esquecidos que estão gerando custo à toa."},
{id:74, m:14, q:"Além do Cost Explorer, qual outra ferramenta ajuda a identificar oportunidades de otimizar (rightsizing) recursos subutilizados?", a:"O AWS Compute Optimizer, que analisa o uso histórico de recursos e recomenda tipos de instância mais adequados ao padrão real de uso."},
{id:75, m:14, q:"O que os Serviços do AWS Support oferecem além de abrir chamados técnicos?", a:"Acesso ao Trusted Advisor (dependendo do plano), Personal Health Dashboard, e orientação proativa sobre arquitetura, custo e segurança, variando por nível de plano contratado."},

// ===== 15. Implantação Automática e Repetível =====
{id:76, m:15, q:"O que é uma AMI (Amazon Machine Image), e por que criar uma 'imagem dourada' (golden image) é uma boa prática?", a:"Uma AMI é um template usado para lançar instâncias EC2; uma golden image já vem com configurações, patches e software pré-instalados, garantindo que toda nova instância nasça consistente e pronta."},
{id:77, m:15, q:"O que um Launch Template do EC2 permite definir?", a:"Configurações padrão para lançar instâncias (tipo de instância, AMI, Security Groups, storage etc.), reutilizáveis em Auto Scaling Groups ou lançamentos manuais, com suporte a versionamento."},
{id:78, m:15, q:"Qual é o principal benefício de Infrastructure as Code (IaC) em relação a configurar recursos manualmente?", a:"Torna o processo repetível, versionável e auditável — o mesmo template sempre gera o mesmo resultado, eliminando inconsistências de configuração manual entre ambientes."},
{id:79, m:15, q:"Qual a principal diferença prática entre escrever um template em JSON versus YAML no CloudFormation?", a:"Ambos fazem a mesma coisa funcionalmente; YAML costuma ser mais legível para humanos (menos chaves e vírgulas), enquanto JSON é mais rígido na sintaxe, mas mais fácil de gerar programaticamente."},
{id:80, m:15, q:"O que é um Change Set no AWS CloudFormation?", a:"Um preview das mudanças que serão aplicadas a uma stack antes de executá-las de fato, permitindo revisar o impacto (o que será criado, modificado ou destruído) com segurança."},
{id:81, m:15, q:"O que significa 'drift' em uma stack do CloudFormation?", a:"Quando o estado real de um recurso na AWS diverge do que está definido no template — por exemplo, alguém alterou manualmente uma configuração que deveria ser controlada só pelo CloudFormation."},
{id:82, m:15, q:"Qual é geralmente a primeira coisa a verificar quando uma stack do CloudFormation falha ao ser criada?", a:"A aba de eventos da stack no Console, que mostra em qual recurso específico o erro ocorreu e a mensagem de falha detalhada, facilitando isolar o problema."}
);
