// Glossário de termos e siglas relevantes para o CLF-C02

GLOSSARY.push(
{term:"IAM", def:"Identity and Access Management — serviço que controla quem está autenticado e autorizado a acessar recursos na conta AWS."},
{term:"MFA", def:"Multi-Factor Authentication — exige um segundo fator de verificação além da senha para autenticação."},
{term:"VPC", def:"Virtual Private Cloud — rede virtual logicamente isolada dentro da AWS, onde você define IPs, sub-redes e rotas."},
{term:"EC2", def:"Elastic Compute Cloud — serviço de servidores virtuais (instâncias) com capacidade redimensionável."},
{term:"S3", def:"Simple Storage Service — armazenamento de objetos durável e escalável."},
{term:"EBS", def:"Elastic Block Store — armazenamento em blocos persistente, anexado a instâncias EC2."},
{term:"EFS", def:"Elastic File System — sistema de arquivos compartilhado, montável por múltiplas instâncias simultaneamente."},
{term:"RDS", def:"Relational Database Service — serviço gerenciado de bancos de dados relacionais (MySQL, PostgreSQL, etc.)."},
{term:"IOPS", def:"Input/Output Operations Per Second — métrica de performance de armazenamento, indicando operações de leitura/escrita por segundo."},
{term:"AZ", def:"Availability Zone — um ou mais data centers isolados dentro de uma Região AWS, com energia e rede redundantes."},
{term:"CIDR", def:"Classless Inter-Domain Routing — notação usada para definir faixas de IP, por exemplo em sub-redes de VPC."},
{term:"ARN", def:"Amazon Resource Name — identificador único usado para referenciar recursos AWS de forma inequívoca."},
{term:"SLA", def:"Service Level Agreement — acordo formal de nível de serviço, geralmente expresso em % de disponibilidade garantida."},
{term:"TCO", def:"Total Cost of Ownership — custo total de propriedade, usado para comparar gastos com nuvem vs infraestrutura própria."},
{term:"CAF", def:"Cloud Adoption Framework — guia de boas práticas da AWS para apoiar a estratégia de adoção da nuvem."},
{term:"DR", def:"Disaster Recovery — estratégias e processos para recuperação de sistemas após desastres ou falhas graves."},
{term:"RTO", def:"Recovery Time Objective — tempo máximo aceitável para restaurar um sistema após uma interrupção."},
{term:"RPO", def:"Recovery Point Objective — quantidade máxima aceitável de perda de dados, medida em tempo, após uma falha."},
{term:"HA", def:"High Availability — alta disponibilidade, prática de arquitetar sistemas para minimizar tempo de inatividade."},
{term:"ELB", def:"Elastic Load Balancing — distribui automaticamente tráfego de entrada entre múltiplos alvos."},
{term:"ASG", def:"Auto Scaling Group — conjunto de instâncias EC2 gerenciado pelo AWS Auto Scaling, que ajusta a quantidade conforme a demanda."},
{term:"CDN", def:"Content Delivery Network — rede de distribuição de conteúdo com baixa latência (na AWS, o Amazon CloudFront)."},
{term:"KMS", def:"Key Management Service — serviço gerenciado para criar e controlar chaves de criptografia."},
{term:"ACM", def:"AWS Certificate Manager — provisiona e gerencia certificados SSL/TLS gratuitamente."},
{term:"WAF", def:"Web Application Firewall — protege aplicações web contra exploits comuns no tráfego HTTP/HTTPS."},
{term:"DDoS", def:"Distributed Denial of Service — ataque que sobrecarrega um sistema com tráfego de múltiplas origens; mitigado pelo AWS Shield."},
{term:"SSO", def:"Single Sign-On — autenticação única que dá acesso a múltiplos sistemas ou contas (na AWS, via IAM Identity Center)."},
{term:"SCP", def:"Service Control Policy — política do AWS Organizations que define o limite máximo de permissões em contas-membro."},
{term:"OU", def:"Organizational Unit — agrupamento de contas no AWS Organizations, usado para aplicar políticas de forma centralizada."},
{term:"PoP", def:"Point of Presence — ponto de presença da rede AWS; inclui as edge locations usadas por serviços como CloudFront."},
{term:"NACL", def:"Network Access Control List — regras de firewall stateless aplicadas no nível da subnet."},
{term:"SG", def:"Security Group — firewall virtual stateful aplicado no nível da instância."},
{term:"ECS", def:"Elastic Container Service — orquestração de containers Docker totalmente gerenciada pela AWS."},
{term:"EKS", def:"Elastic Kubernetes Service — serviço gerenciado para rodar Kubernetes na AWS."},
{term:"Lambda", def:"Serviço de computação serverless que executa código em resposta a eventos, sem gerenciamento de servidores."},
{term:"Fargate", def:"Mecanismo de computação serverless para containers, usado com ECS ou EKS."},
{term:"SaaS", def:"Software as a Service — modelo onde o software é entregue pronto para uso, sem gerenciar infraestrutura ou plataforma."},
{term:"PaaS", def:"Platform as a Service — modelo onde a plataforma (runtime, ferramentas) é gerenciada pelo provedor; você foca só na aplicação."},
{term:"IaaS", def:"Infrastructure as a Service — modelo onde você gerencia o sistema operacional e acima, e o provedor cuida do hardware físico."},
{term:"CapEx", def:"Capital Expenditure — investimento inicial alto em ativos físicos, como hardware comprado antecipadamente."},
{term:"OpEx", def:"Operational Expenditure — despesa operacional variável, paga conforme o uso, sem investimento inicial alto."},
{term:"Free Tier", def:"Camada gratuita da AWS, com acesso limitado a diversos serviços por 12 meses ou de forma sempre gratuita, dependendo do serviço."},
{term:"TAM", def:"Technical Account Manager — gerente técnico dedicado, disponível para clientes do plano de suporte Enterprise."},
{term:"SOC", def:"System and Organization Controls — tipo de relatório de auditoria de conformidade, disponível via AWS Artifact."},
{term:"PCI-DSS", def:"Payment Card Industry Data Security Standard — padrão de segurança para empresas que processam dados de cartão de crédito."},
{term:"HIPAA", def:"Health Insurance Portability and Accountability Act — lei americana de proteção de dados de saúde."},
{term:"GDPR", def:"General Data Protection Regulation — regulamento europeu de proteção de dados pessoais."},
{term:"BAA", def:"Business Associate Addendum — acordo relacionado à conformidade HIPAA, disponível via AWS Artifact."},
{term:"RI", def:"Reserved Instance — compromisso de uso de 1 ou 3 anos em troca de desconto significativo no EC2."},
{term:"On-Demand", def:"Modelo de precificação sem compromisso, cobrando por hora ou segundo de uso, ideal para cargas imprevisíveis."},
{term:"Spot Instance", def:"Capacidade EC2 ociosa vendida com desconto de até 90%, podendo ser interrompida pela AWS com pouco aviso."},
{term:"Savings Plan", def:"Modelo de desconto flexível baseado em compromisso de gasto (USD/hora) por 1 ou 3 anos."},
{term:"S3 Glacier", def:"Classe de armazenamento S3 de baixo custo para arquivamento de longo prazo, com acesso pouco frequente."},
{term:"DynamoDB", def:"Banco de dados NoSQL serverless de chave-valor, com performance de milissegundos em qualquer escala."},
{term:"Aurora", def:"Banco de dados relacional da AWS, compatível com MySQL/PostgreSQL, com performance superior aos engines tradicionais."},
{term:"Redshift", def:"Serviço de data warehouse gerenciado, otimizado para análise de grandes volumes de dados."},
{term:"CloudTrail", def:"Serviço que registra todas as chamadas de API feitas na conta, usado para auditoria e investigação de segurança."},
{term:"CloudWatch", def:"Serviço de monitoramento que coleta métricas, logs e eventos, permitindo dashboards e alarmes."},
{term:"Config", def:"AWS Config — avalia, audita e registra continuamente as configurações dos recursos AWS."},
{term:"Trusted Advisor", def:"Ferramenta que analisa a conta AWS e sugere melhorias em custo, performance, segurança e tolerância a falhas."},
{term:"Organizations", def:"AWS Organizations — serviço para gerenciar e governar centralmente múltiplas contas AWS."},
{term:"Consolidated Billing", def:"Funcionalidade do AWS Organizations que combina o faturamento de múltiplas contas em uma única fatura."},
{term:"Snowball", def:"Dispositivo físico da AWS Snow Family usado para transportar grandes volumes de dados para a nuvem."},
{term:"Direct Connect", def:"Conexão de rede privada e dedicada entre o data center on-premises e a AWS."},
{term:"Route 53", def:"Serviço de DNS gerenciado e escalável da AWS, também usado para registro de domínios."},
{term:"CloudFront", def:"Rede de distribuição de conteúdo (CDN) da AWS, que usa edge locations para baixa latência."},
{term:"SNS", def:"Simple Notification Service — serviço de mensageria pub/sub para notificações a múltiplos assinantes."},
{term:"SQS", def:"Simple Queue Service — serviço de filas de mensagens usado para desacoplar componentes de aplicações."},
{term:"CloudFormation", def:"Serviço de Infrastructure as Code que provisiona recursos AWS via templates declarativos (JSON/YAML)."},
{term:"Elastic Beanstalk", def:"Serviço que automatiza o deploy e provisionamento de infraestrutura para aplicações."},
{term:"Outposts", def:"Permite rodar infraestrutura e serviços nativos da AWS fisicamente on-premises."},
{term:"Well-Architected Framework", def:"Conjunto de boas práticas organizadas em 6 pilares para projetar arquiteturas robustas na AWS."},
{term:"Shared Responsibility Model", def:"Modelo que divide responsabilidades de segurança entre a AWS (segurança 'da' nuvem) e o cliente (segurança 'na' nuvem)."},
{term:"Region", def:"Localização física que agrupa múltiplas Availability Zones isoladas entre si."},
{term:"Edge Location", def:"Ponto de presença da AWS usado para cache e entrega de conteúdo com baixa latência."},
{term:"GuardDuty", def:"Serviço de detecção de ameaças que monitora atividade maliciosa usando machine learning."},
{term:"Macie", def:"Serviço que descobre e classifica dados sensíveis armazenados no Amazon S3, usando machine learning."},
{term:"Inspector", def:"Serviço de avaliação automatizada de vulnerabilidades em EC2 e imagens de containers."},
{term:"Shield", def:"Serviço de proteção contra ataques DDoS, disponível nas versões Standard (gratuita) e Advanced (paga)."},
{term:"Secrets Manager", def:"Serviço para armazenar, gerenciar e rotacionar credenciais como senhas e chaves de API."},
{term:"Artifact", def:"Portal de autoatendimento com relatórios de conformidade e acordos de segurança da AWS."},
{term:"SageMaker", def:"Serviço totalmente gerenciado para construir, treinar e implantar modelos de machine learning."},
{term:"Bedrock", def:"Serviço que dá acesso via API a modelos fundacionais de IA generativa de diversas empresas."},
{term:"IAM Access Analyzer", def:"Identifica quando um bucket S3, uma IAM role ou outro recurso foi compartilhado com uma entidade externa à conta ou organização."},
{term:"Credential Report", def:"Relatório do IAM que lista todos os usuários da conta e o status de suas credenciais (senha, MFA, idade das access keys), usado em auditorias."},
{term:"EC2 Image Builder", def:"Serviço que automatiza a criação, teste e manutenção de AMIs (imagens) personalizadas e padronizadas do EC2."},
{term:"VPC Flow Logs", def:"Registros do tráfego de rede (IP) que entra e sai das interfaces de rede dentro de uma VPC, usados para diagnóstico e investigação de segurança."},
{term:"AWS Batch", def:"Serviço totalmente gerenciado para executar cargas de trabalho de processamento em lote (batch) em qualquer escala, sem gerenciar a infraestrutura subjacente."},
{term:"Versionamento (S3)", def:"Recurso do S3 que mantém múltiplas versões de um objeto, protegendo contra exclusão ou substituição acidental."},
{term:"AWS CAF — Envision", def:"Primeira fase da jornada de transformação do AWS CAF: identificar e priorizar oportunidades de transformação alinhadas a objetivos estratégicos do negócio."},
{term:"AWS CAF — Align", def:"Fase do AWS CAF focada em identificar lacunas de capacidade entre as 6 perspectivas e dependências entre áreas, antes de partir para pilotos."},
{term:"AWS CAF — Launch", def:"Fase do AWS CAF focada em entregar pilotos em produção e demonstrar valor de negócio incremental."},
{term:"AWS CAF — Scale", def:"Última fase do AWS CAF: expandir os pilotos bem-sucedidos e o valor de negócio para a escala desejada em toda a organização."}
);
